[env:pool-switch-esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.flash_size = 4MB
board_build.embed_txtfiles =
	src/index.html
extra_scripts = pre:version.py
